SELECT USER_ID, NICKNAME,
       CONCAT(CITY,' ',STREET_ADDRESS1,' ',STREET_ADDRESS2) AS 전체주소,
       CONCAT(LEFT(TLNO,3), '-', MID(TLNO,4,4),'-', RIGHT(TLNO,4)) AS 전화번호
FROM USED_GOODS_USER
         JOIN
     (SELECT WRITER_ID, COUNT(*) AS CNT FROM USED_GOODS_BOARD
      GROUP BY WRITER_ID HAVING CNT>=3) GOODS
     ON USER_ID = WRITER_ID
ORDER BY USER_ID DESC;
