WITH VALUE AS (
    SELECT CAR.DAILY_FEE, CAR.CAR_TYPE, HISTORY.HISTORY_ID,
           DATEDIFF(END_DATE,START_DATE) + 1 AS PERIOD,
           CASE
               WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 90 THEN '90일 이상'
               WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 30 THEN '30일 이상'
               WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 7 THEN '7일 이상'
               ELSE 'NONE' END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR AS CAR
             INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY USING(CAR_ID)
    WHERE CAR.CAR_TYPE = '트럭')



SELECT value.HISTORY_ID,
    ROUND(value.DAILY_FEE * value. PERIOD*
          (100 - IFNULL(PLAN.DISCOUNT_RATE,0)) / 100) AS FEE
FROM VALUE
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
ON PLAN.DURATION_TYPE=VALUE.DURATION_TYPE
    AND PLAN.CAR_TYPE=VALUE.CAR_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC;