SELECT APNT_NO,PT_NAME,PT_NO,APPOINTMENT.MCDP_CD AS MCDP_CD,DR_NAME,APNT_YMD
FROM APPOINTMENT
         JOIN PATIENT USING (PT_NO)
         JOIN DOCTOR ON DOCTOR.DR_ID = APPOINTMENT.MDDR_ID
WHERE APPOINTMENT.MCDP_CD = 'CS'
  AND APNT_CNCL_YMD IS NULL
  AND APNT_YMD LIKE "2022-04-13%"
ORDER BY APPOINTMENT.APNT_YMD;