SELECT
FOOD_PRODUCT.PRODUCT_ID AS PRODUCT_ID,
PRODUCT_NAME,
PRICE * AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT
JOIN
(
SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
FROM FOOD_ORDER
WHERE YEAR(PRODUCE_DATE)=2022 AND MONTH(PRODUCE_DATE)=5
GROUP BY PRODUCT_ID
HAVING SUM(AMOUNT)
) AS FOOD_ORDER
USING(PRODUCT_ID)
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;