SELECT
ANIMAL_INS.ANIMAL_ID AS ANIMAL_ID,
ANIMAL_INS.ANIMAL_TYPE AS ANIAML_TYPE,
ANIMAL_INS.NAME AS NAME
FROM ANIMAL_INS JOIN ANIMAL_OUTS USING(ANIMAL_ID)
WHERE SEX_UPON_INTAKE != SEX_UPON_OUTCOME
ORDER BY ANIMAL_ID ASC;
