SELECT
BOOK.AUTHOR_ID AS AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE*SALES) AS TOTAL_SALES
FROM BOOK JOIN BOOK_SALES USING(BOOK_ID) JOIN AUTHOR USING(AUTHOR_ID)
WHERE YEAR(SALES_DATE)=2022 AND MONTH(SALES_DATE)=1
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;